name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

  #  - name: Set up Node.js
  #    uses: actions/setup-node@v2
  #    with:
  #      node-version: '16' # Specify Node.js 16

  #  - name: Build project
  #    run: npm run build

    # Replace the API key placeholder in the built files.
    # Ensure that the path to your built files is correctly specified.
    - name: Replace API key placeholder
      run: |
        sed -i 's/API_KEY/${{ secrets.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 }}/g' LGPT/chat.js

    # Add additional steps for deployment if necessary.
    # For example, if deploying to GitHub Pages, you might use a specific action for that.

