name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Specify Node.js 16

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    # Replace the API key placeholder in the built files.
    # Ensure that the path to your built files is correctly specified.
    - name: Replace API key placeholder
      run: |
        sed -i 's/API_KEY/${{ secrets.API_KEY }}/g' path/to/your/built/files

    # Add additional steps for deployment if necessary.
    # For example, if deploying to GitHub Pages, you might use a specific action for that.
    - name: Deploy
      uses: Loart/Loart.github.io
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        # Other deployment configurations go here.
